Repository PublicRadioInternational/pri-component-library, pull requests merged in 2018-03, with the labels that each got.

#26 PRIAPI-128: Card List
  index.js
  src/components/00_global/colors.css
  src/components/Molecules/CardItem/CardItem.component.js
  src/components/Molecules/CardItem/CardItem.css
  src/components/Molecules/CardItem/CardItem.test.js
  src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
  src/components/Molecules/molecules.story.js
  src/components/Organisms/CardList/CardList.component.js
  src/components/Organisms/CardList/CardList.css
  src/components/Organisms/CardList/CardList.test.js
  src/components/Organisms/CardList/__snapshots__/CardList.test.js.snap
  src/components/Organisms/organisms.story.js
Labels: Passes PO review, passes code review, passes functional review

#30 HOTFIX: Update CardList categories
  src/components/00_global/colors.css
  src/components/Organisms/CardList/CardList.component.js
Labels: Passes PO review, passes code review, passes functional review

#27 PIRAPI-126: Featured Story molecule
  index.js
  package.json
  src/components/00_global/global.css
  src/components/Atoms/Button/Button.component.js
  src/components/Atoms/Button/ButtonInput.component.js
  src/components/Atoms/Button/ButtonLink.component.js
  src/components/Atoms/Button/__snapshots__/Button.test.js.snap
  src/components/Atoms/Svg/Icons.component.js
  src/components/Atoms/Svg/Icons.css
  src/components/Atoms/Svg/PriLogo.component.js
  src/components/Atoms/Svg/__snapshots__/Icons.test.js.snap
  src/components/Molecules/Accordion/Accordion.component.js
  src/components/Molecules/Accordion/__snapshots__/Accordion.test.js.snap
  src/components/Molecules/CardItem/CardItem.component.js
  src/components/Molecules/CardItem/CardItem.css
  src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
  src/components/Molecules/Hero/Hero.component.js
  src/components/Molecules/Hero/Hero.css
  src/components/Molecules/Hero/Hero.test.js
  src/components/Molecules/Hero/__snapshots__/Hero.test.js.snap
  src/components/Molecules/Hero/images/bg.png
  src/components/Molecules/List/List.component.js
  src/components/Molecules/List/__snapshots__/List.test.js.snap
  src/components/Molecules/Search/__snapshots__/Search.test.js.snap
  src/components/Molecules/molecules.story.js
  src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap
  src/components/Organisms/Header/Header.component.js
  src/components/Organisms/Header/__snapshots__/Header.test.js.snap
  src/components/Organisms/Header/__snapshots__/MainMenu.test.js.snap
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes code review, passes functional review

#31 HOTFIX: All Hero program links to have a different url.
  src/components/Molecules/Hero/Hero.component.js
  src/components/Molecules/Hero/Hero.test.js
  src/components/Molecules/Hero/__snapshots__/Hero.test.js.snap
  src/components/Molecules/molecules.story.js
Labels: passes PO review, passes functional review

#32 PRIAPI-141: Add Storybook a11l support
  .nvmrc
  .storybook/addons.js
  package.json
  src/components/Atoms/atoms.story.js
  src/components/Molecules/molecules.story.js
  src/components/Organisms/organisms.story.js
  src/components/Pages/page.story.js
  yarn.lock
Labels: passes code review, passes functional review

#34 HOTFIX: Url and title not required in CardItem
  src/components/Molecules/CardItem/CardItem.component.js
  src/components/Molecules/CardItem/CardItem.test.js
  src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
  src/components/Organisms/CardList/CardList.component.js
  src/components/Organisms/organisms.story.js
Labels: passes code review, passes functional review

#36 HOTFIX: Update card list header colors
  src/components/Organisms/CardList/CardList.css
  src/components/Organisms/organisms.story.js
Labels: passes code review, passes functional review
