Repository PublicRadioInternational/pri-component-library, pull requests merged in 2018-04, with the labels that each got.

#35 PRIAPI-130: Add components for Latest content sidebar
  index.js
  src/components/00_global/colors.css
  src/components/Atoms/Button/Button.css
  src/components/Atoms/Button/ButtonLink.component.js
  src/components/Molecules/Teaser/TeaserItem.component.js
  src/components/Molecules/Teaser/TeaserItem.css
  src/components/Molecules/Teaser/TeaserItem.test.js
  src/components/Molecules/Teaser/__snapshots__/TeaserItem.test.js.snap
  src/components/Molecules/molecules.story.js
  src/components/Organisms/Teaser/TeaserList.component.js
  src/components/Organisms/Teaser/TeaserList.css
  src/components/Organisms/Teaser/TeaserList.test.js
  src/components/Organisms/Teaser/__snapshots__/TeaserList.test.js.snap
  src/components/Organisms/organisms.story.js
Labels: passes PO review, passes code review, passes functional review

#37 HOTFIX: Freeform CardItem styles
  package.json
  src/components/Molecules/CardItem/CardItem.component.js
  src/components/Molecules/CardItem/CardItem.css
  src/components/Molecules/CardItem/CardItem.test.js
  src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
  src/components/Molecules/molecules.story.js
  yarn.lock
Labels: passes PO review, passes code review, passes functional review

#39 fix(layout): grid tweaks to match prototype
  src/components/Organisms/Main/Main.css
Labels: passes code review, passes functional review

#41 PRIAPI-128: medium layout and responsive fixes
  src/components/00_global/global.css
  src/components/Organisms/Main/Main.css
Labels: passes code review, passes functional review

#42 HOTFIX: add blockquote style
  src/components/00_global/global.css
  src/components/Molecules/molecules.story.js
Labels: passes code review, passes functional review

#40 PRIAPI-132: Quick links
  index.js
  src/components/Molecules/Accordion/__snapshots__/Accordion.test.js.snap
  src/components/Molecules/List/List.component.js
  src/components/Molecules/List/List.css
  src/components/Molecules/List/__snapshots__/List.test.js.snap
  src/components/Molecules/MenuList/MenuList.component.js
  src/components/Molecules/MenuList/MenuList.css
  src/components/Molecules/MenuList/MenuList.test.js
  src/components/Molecules/MenuList/__snapshots__/MenuList.test.js.snap
  src/components/Molecules/molecules.story.js
  src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap
  src/components/Organisms/Header/__snapshots__/Header.test.js.snap
  src/components/Organisms/Header/__snapshots__/MainMenu.test.js.snap
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes PO review, passes functional review, ready for review

#44 PIRAPI-128: Homepage CardList video auto height
  src/components/00_global/global.css
  src/components/Molecules/CardItem/CardItem.component.js
  src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
Labels: passes code review, passes functional review

#43 PRIAPI-133: About block
  index.js
  src/components/00_global/colors.css
  src/components/00_global/global.css
  src/components/Atoms/Button/Button.css
  src/components/Molecules/TextBlock/TextBlock.component.js
  src/components/Molecules/TextBlock/TextBlock.css
  src/components/Molecules/TextBlock/TextBlock.test.js
  src/components/Molecules/TextBlock/__snapshots__/TextBlock.test.js.snap
  src/components/Molecules/molecules.story.js
Labels: passes PO review, passes code review, passes functional review

#46 Home content
  src/components/Molecules/MenuList/MenuList.css
  src/components/Molecules/TextBlock/TextBlock.css
  src/components/Organisms/Main/Main.css
  src/components/Pages/Home/Home.component.js
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes code review, passes functional review

#45 HOTFIX: Freeform blurb is div and has no margin
  src/components/Molecules/CardItem/CardItem.component.js
  src/components/Molecules/CardItem/CardItem.css
  src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
Labels: passes PO review, passes code review, passes functional review

#47 HOTFIX: tweak teaserList header style
  src/components/Molecules/CardItem/CardItem.component.js
  src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
  src/components/Organisms/Teaser/TeaserList.css
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes code review, passes functional review

#48 PRIAPI-134: Block List component
  index.js
  src/components/Atoms/Button/Button.css
  src/components/Atoms/Form/Form.css
  src/components/Molecules/TextBlock/TextBlock.component.js
  src/components/Molecules/TextBlock/TextBlock.css
  src/components/Molecules/TextBlock/TextBlock.test.js
  src/components/Molecules/TextBlock/__snapshots__/TextBlock.test.js.snap
  src/components/Molecules/molecules.story.js
  src/components/Organisms/BlockList/BlockList.component.js
  src/components/Organisms/BlockList/BlockList.css
  src/components/Organisms/BlockList/BlockList.test.js
  src/components/Organisms/BlockList/__snapshots__/BlockList.test.js.snap
  src/components/Organisms/Footer/Footer.css
  src/components/Organisms/Main/Main.css
  src/components/Organisms/organisms.story.js
  src/components/Pages/Home/Home.component.js
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes PO review, passes code review, passes functional review

#50 PRIAPI-134: button fixes
  src/components/Atoms/Button/Button.css
  src/components/Organisms/organisms.story.js
  src/components/Pages/Home/Home.component.js
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes code review, passes functional review

#38 PRIAPI-156: Add CTA Message component
  index.js
  src/components/00_global/colors.css
  src/components/Atoms/Button/Button.component.js
  src/components/Atoms/Button/Button.css
  src/components/Atoms/Svg/Icons.component.js
  src/components/Molecules/CtaMessage/CtaMessage.component.js
  src/components/Molecules/CtaMessage/CtaMessage.css
  src/components/Molecules/CtaMessage/CtaMessage.test.js
  src/components/Molecules/CtaMessage/__snapshots__/CtaMessage.test.js.snap
  src/components/Molecules/molecules.story.js
Labels: passes PO review, passes functional review

#52 PRIAPI-131: Sticky component
  index.js
  package.json
  src/components/Molecules/StickyItem/StickyItem.component.js
  src/components/Molecules/StickyItem/StickyItem.css
  src/components/Organisms/CardList/CardList.css
  src/components/Organisms/Main/Main.css
  src/components/Pages/Home/Home.component.js
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
  yarn.lock
Labels: passes PO review, passes code review, passes functional review

#55 Hotfix/sticky lib loading
  package.json
  src/components/Molecules/StickyItem/StickyItem.component.js
  src/components/Molecules/StickyItem/StickyItem.css
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes code review, passes functional review

#53 PRIAPI-158: consistent card list title height
  src/components/Organisms/CardList/CardList.component.js
  src/components/Organisms/CardList/CardList.css
  src/components/Organisms/CardList/__snapshots__/CardList.test.js.snap
  src/components/Organisms/organisms.story.js
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes PO review, passes code review, passes functional review

#56 fix: set innerHtml for CardItem blurbs
  package.json
  src/components/Molecules/CardItem/CardItem.component.js
  src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
  src/components/Molecules/molecules.story.js
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
  yarn.lock
Labels: passes code review, passes functional review

#61 PRIAPI-153: Lazy Load
  .babelrc
  .storybook/config.js
  __mocks__/intersection-observer.js
  index.js
  package.json
  src/components/00_global/global.css
  src/components/Atoms/LazyLoad/LazyLoad.component.js
  src/components/Molecules/CardItem/CardItem.component.js
  src/components/Molecules/CardItem/CardItem.test.js
  src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
  src/components/Molecules/Hero/Hero.component.js
  src/components/Molecules/Hero/Hero.test.js
  src/components/Molecules/Hero/__snapshots__/Hero.test.js.snap
  src/components/Pages/Home/Home.test.js
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
  yarn.lock
Labels: passes PO review, passes code review, passes functional review

#63 fix(ssr): only load polyfill in browser
  src/components/Atoms/LazyLoad/LazyLoad.component.js
Labels: passes code review, passes functional review

#65 HOTFIX: fix padding in load under
  src/components/Molecules/CtaMessage/CtaMessage.css
  src/components/Molecules/molecules.story.js
Labels: passes code review, passes functional review

#66 PRIAPI-165: reorder styles in accordion
  src/components/Molecules/Accordion/Accordion.component.js
Labels: ready for review

#58 PRIAPI-161: NPM publish
  package.json
  src/components/Molecules/CardItem/CardItem.component.js
Labels: passes code review, ready for review

#64 PRIAPI-151: More robust tests
  src/components/Atoms/Button/Button.test.js
  src/components/Atoms/Button/__snapshots__/Button.test.js.snap
  src/components/Atoms/LazyLoad/LazyLoad.test.js
  src/components/Atoms/LazyLoad/__snapshots__/LazyLoad.test.js.snap
  src/components/Atoms/Svg/Icons.component.js
  src/components/Atoms/Svg/Icons.test.js
  src/components/Atoms/Svg/__snapshots__/Icons.test.js.snap
  src/components/Molecules/CardItem/CardItem.component.js
  src/components/Molecules/CardItem/CardItem.test.js
  src/components/Molecules/CardItem/__snapshots__/CardItem.test.js.snap
  src/components/Molecules/Dropdown/Dropdown.test.js
  src/components/Molecules/Hero/Hero.component.js
  src/components/Molecules/Hero/Hero.test.js
  src/components/Molecules/Hero/__snapshots__/Hero.test.js.snap
  src/components/Molecules/Search/Search.component.js
  src/components/Organisms/Main/Main.test.js
  src/components/Organisms/Main/__snapshots__/Main.test.js.snap
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes code review, passes functional review

#72 HOTFIX: Update load under title style to match live changes
  src/components/Molecules/CtaMessage/CtaMessage.component.js
  src/components/Molecules/CtaMessage/CtaMessage.css
  src/components/Molecules/CtaMessage/__snapshots__/CtaMessage.test.js.snap
Labels: passes PO review, passes code review, passes functional review

#74 HOTFIX: Header donate link url
  src/components/Organisms/Header/Header.component.js
  src/components/Organisms/Header/__snapshots__/Header.test.js.snap
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: bug, ready for review

#75 PRIAPI-174: Standardize UI z-index scheme
  src/components/00_global/stratas.css
  src/components/Molecules/CtaMessage/CtaMessage.css
  src/components/Molecules/Dropdown/Dropdown.css
  src/components/Molecules/Hero/Hero.css
  src/components/Organisms/Header/Header.css
  src/components/Organisms/Main/Main.css
  src/components/Pages/Home/Home.component.js
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes PO review, passes code review, passes functional review

#77 HOTFIX: Remove storybook action from Home component
  src/components/Pages/Home/Home.component.js
Labels: passes code review, ready for review

#79 HOTFIX: footer links mixed up
  src/components/Organisms/Footer/Footer.component.js
  src/components/Organisms/Footer/__snapshots__/Footer.test.js.snap
  src/components/Organisms/organisms.story.js
  src/components/Pages/Home/Home.component.js
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes PO review, passes code review, passes functional review
