Repository PublicRadioInternational/pri-component-library, pull requests merged in 2018-06, with the labels that each got.

#85 fix(ctamessage): render dismiss button when action note defined
  src/components/Molecules/CtaMessage/CtaMessage.component.js
Labels: passes functional review

#87 HOTFIX: CTA Message action url is optional
  src/components/Molecules/CtaMessage/CtaMessage.component.js
  src/components/Molecules/molecules.story.js
Labels: passes functional review

#89 PRISB-295: add Quick Link colors for Takeaway and LOE
  src/components/00_global/colors.css
  src/components/Molecules/List/List.css
  src/components/Molecules/molecules.story.js
Labels: ready for review

#90 Release June 12, 2018
  src/components/00_global/colors.css
  src/components/Molecules/List/List.css
  src/components/Molecules/molecules.story.js
Labels: ready for review

#91 PRISB-303: fix typo in main menu
  src/components/Organisms/Header/MainMenu.component.js
  src/components/Organisms/Header/__snapshots__/Header.test.js.snap
  src/components/Organisms/Header/__snapshots__/MainMenu.test.js.snap
  src/components/Pages/Home/__snapshots__/Home.test.js.snap
Labels: passes code review, passes functional review
